const MEMORY_FORMAT = 'json';

enum KERNEL {
    NAME = 'Eeems\'screeps',
    VERSION = '0.0.1'
}

enum SEGMENTS {
    KERNEL = 0,
    INTERRUPT,
    DEVICES
}

enum INTERRUPT {
    TICKSTART = 0,
    TICKEND,
    DEINIT,
    SEGMENT,
    CREEP,
    VISION,
    PROCSTART,
    PROCKILL
}

enum INTERRUPT_TYPE {
    INTERRUPT = 1,
    WAKE
}

enum BUILDING_LIMITS {
    CONTAINERS = 5
}

const ERROR_MESSAGES  = {};
ERROR_MESSAGES[OK] = 'Okay';
ERROR_MESSAGES[ERR_NOT_OWNER] = 'Not Owner';
ERROR_MESSAGES[ERR_NO_PATH] = 'No Path';
ERROR_MESSAGES[ERR_NAME_EXISTS] = 'Name Exists';
ERROR_MESSAGES[ERR_BUSY] = 'Busy';
ERROR_MESSAGES[ERR_NOT_FOUND] = 'Not Found';
ERROR_MESSAGES[ERR_NOT_ENOUGH_RESOURCES] = 'Not Enough Resources';
ERROR_MESSAGES[ERR_INVALID_TARGET] = 'Invalid Target';
ERROR_MESSAGES[ERR_FULL] = 'Full';
ERROR_MESSAGES[ERR_NOT_IN_RANGE] = 'Not In Range';
ERROR_MESSAGES[ERR_INVALID_ARGS] = 'Invalid Args';
ERROR_MESSAGES[ERR_TIRED] = 'Tired';
ERROR_MESSAGES[ERR_NO_BODYPART] = 'No Bodypart';
ERROR_MESSAGES[ERR_RCL_NOT_ENOUGH] = 'RCL Not Enough';
ERROR_MESSAGES[ERR_GCL_NOT_ENOUGH] = 'GCL Not Enough';

export default {
    BUILDING_LIMITS,
    ERROR_MESSAGES,
    INTERRUPT,
    INTERRUPT_TYPE,
    KERNEL,
    MEMORY_FORMAT,
    SEGMENTS
};
